workflows:
  build_apk:
    name: Flutter APK Build
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build release APK
        script: |
          flutter build apk --release

      - name: Show built APK path
        script: |
          find build -name "*.apk"

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
