workflows:
  build_apk:
    environment:
      flutter: "3.29.3"
    scripts:
      - name: Install Android Build Tools 34
        script: |
          sdkmanager "build-tools;34.0.0" || true
      - name: Checkout code
        script: |
          flutter --version
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
