workflows:
  android-build:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - name: Clean Project
        script: |
          flutter clean
      - name: Install Dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --no-tree-shake-icons --verbose
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - 2937582423@qq.com # 替换为你的邮箱