workflows:
  build_apk:
    name: Build Android APK
    environment:
      flutter: "3.29.3"
    scripts:
      - name: Checkout code
        script: |
          echo "Using Flutter SDK version:"
          flutter --version

      - name: Install dependencies
        script: |
          flutter pub remove flutter_lints
          flutter pub add --dev flutter_lints:^4.0.0
          flutter pub get

      - name: Build release APK
        script: |
          flutter build apk --release --no-shrink

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
